const ErrorCodeEnum =
{
    UNKNOWN_SERVER_ERROR: -1,
    SUCCESS: 0,
    USERNAME_EXISTS: 1,
    EMAIL_INVALID: 2,
    BAD_JSON_OBJECT: 3,
    WRONG_PASSWORD: 4,
    TOKEN_EXPIRED: 5,
    TOKEN_INVALID: 6,
    USERNAME_DOESNT_EXIST: 7,
    BAD_QUERY_STRING: 8
};

module.exports = ErrorCodeEnum;
